### ISSUE TITLE
java.util.zip.ZipException:error in opening zip file

### ISSUE THREAD

**Issue by 827Dream** [FlyingYu-Z/ApkEncryptor#1]
### 问题展示
![error](https://user-images.githubusercontent.com/52020508/111756954-c20d5f80-88d5-11eb-9662-77b0f0d5bf5e.png)

####  最终发现是在调用EncryptorConfig.java（80）报的错误
```
              File apk=new File(MyApp.getContext().getFilesDir()+File.separator+"sub.apk");

              ZipFile zipFile=new ZipFile(apk); //把apk当作zip打开出现上述异常
```
但是这个sub.apk在是在位置ShellSubTask.java（80）创建的
```
		File apk=new File(MyApp.getContext().getFilesDir()+File.separator+"sub.apk");
		FileUtils.mkdir(apk.getParent());
		BYProtectUtils.copyAssetsFile("sub.apk",apk.getAbsolutePath());
```
应该是拷贝了资源文件（MD5:89122AB303A8DA6FC5694C6BAD48229E ）到sub.apk当中？才导致后面当作zip解析不正确？

**Comment by FlyingYu-Z** [comment]
项目当中有assets和assets_en两个文件夹，assets_en是assets加密后的结果

如果采用assets目录的资源，则改写BYProtectUtils.copyAssetsFile("sub.apk",apk.getAbsolutePath());
去掉文件名md5

**Comment by FlyingYu-Z** [comment]
我已经解决了这个问题，请重新拉代码（BYProtectUtils、build.gradle）编译

**Comment by 827Dream** [comment]
好的，谢谢！
